import { provincia } from './provincia';

interface Cantones {
  [key: string]: { [key: string]: { code: string; label: string } };
}

export const cantones: Cantones = {
  NACIONALIZADOS: {},
  AZUAY: {
    CUENCA: { code: '01', label: 'Cuenca' },
    GIRON: { code: '02', label: 'Giron' },
    GUALACEO: { code: '03', label: 'Gualaceo' },
    NABON: { code: '04', label: 'Nabon' },
    PAUTE: { code: '05', label: 'Paute' },
    PUCARA: { code: '06', label: 'Pucará' },
    SAN_FERNANDO: { code: '07', label: 'San Fernando' },
    SANTA_ISABEL: { code: '08', label: 'Santa Isabel' },
    SIGSIG: { code: '09', label: 'Sigsig' },
    ONA: { code: '10', label: 'Oña' },
    CHORDELEG: { code: '11', label: 'Chordeleg' },
    EL_PAN: { code: '12', label: 'El Pan' },
    SEVILLA_DE_ORO: { code: '13', label: 'Sevilla De Oro' },
    GUACHAPALA: { code: '14', label: 'Guachapala' },
    CAMILO_PONCE_ENRIQUEZ: { code: '15', label: 'Camilo Ponce Enriquez' },
  },
  BOLIVAR: {
    GUARANDA: { code: '01', label: 'Guaranda' },
    CHILLANES: { code: '02', label: 'Chillanes' },
    CHIMBO: { code: '03', label: 'Chimbo' },
    ECHEANDIA: { code: '04', label: 'Echeandía' },
    SAN_MIGUEL: { code: '05', label: 'San Miguel' },
    CALUMA: { code: '06', label: 'Caluma' },
    LAS_NAVES: { code: '07', label: 'Las Naves' },
  },
  CANAR: {
    AZOGUES: { code: '01', label: 'Azogues' },
    BIBLIAN: { code: '02', label: 'Biblián' },
    CANAR: { code: '03', label: 'Cañar' },
    LA_TRONCAL: { code: '04', label: 'La Troncal' },
    EL_TAMBO: { code: '05', label: 'El Tambo' },
    DELEG: { code: '06', label: 'Déleg' },
    SUSCAL: { code: '07', label: 'Suscal' },
  },
  CARCHI: {
    TULCAN: { code: '01', label: 'Tulcán' },
    BOLIVAR: { code: '02', label: 'Bolívar' },
    ESPEJO: { code: '03', label: 'Espejo' },
    MIRA: { code: '04', label: 'Mira' },
    MONTUFAR: { code: '05', label: 'Montúfar' },
    SAN_PEDRO_DE_HUACA: { code: '06', label: 'San Pedro De Huaca' },
  },
  COTOPAXI: {
    LATACUNGA: { code: '01', label: 'Latacunga' },
    LA_MANA: { code: '02', label: 'La Maná' },
    PANGUA: { code: '03', label: 'Pangua' },
    PUJILI: { code: '04', label: 'Pujilí' },
    SALCEDO: { code: '05', label: 'Salcedo' },
    SAQUISILI: { code: '06', label: 'Saquisilí' },
    SIGCHOS: { code: '07', label: 'Sigchos' },
  },
  CHIMBORAZO: {
    RIOBAMBA: { code: '01', label: 'Riobamba' },
    ALAUSI: { code: '02', label: 'Alausí' },
    COLTA: { code: '03', label: 'Colta' },
    CHAMBO: { code: '04', label: 'Chambo' },
    CHUNCHI: { code: '05', label: 'Chunchi' },
    GUAMOTE: { code: '06', label: 'Guamote' },
    GUANO: { code: '07', label: 'Guano' },
    PALLATANGA: { code: '08', label: 'Pallatanga' },
    PENIPE: { code: '09', label: 'Penipe' },
    CUMANDA: { code: '10', label: 'Cumandá' },
  },
  EL_ORO: {
    MACHALA: { code: '01', label: 'Machala' },
    ARENILLAS: { code: '02', label: 'Arenillas' },
    ATAHUALPA: { code: '03', label: 'Atahualpa' },
    BALSAS: { code: '04', label: 'Balsas' },
    CHILLA: { code: '05', label: 'Chilla' },
    EL_GUABO: { code: '06', label: 'El Guabo' },
    HUAQUILLAS: { code: '07', label: 'Huaquillas' },
    MARCABELI: { code: '08', label: 'Marcabelí' },
    PASAJE: { code: '09', label: 'Pasaje' },
    PINAS: { code: '10', label: 'Piñas' },
    PORTOVELO: { code: '11', label: 'Portovelo' },
    SANTA_ROSA: { code: '12', label: 'Santa Rosa' },
    ZARUMA: { code: '13', label: 'Zaruma' },
    LAS_LAJAS: { code: '14', label: 'Las Lajas' },
  },
  ESMERALDAS: {
    LA_CONCORDIA: { code: '08', label: 'La Concordia' },
    ESMERALDAS: { code: '01', label: 'Esmeraldas' },
    ELOY_ALFARO: { code: '02', label: 'Eloy Alfaro' },
    MUSINE: { code: '03', label: 'Musine' },
    QUININDE: { code: '04', label: 'Quinindé' },
    SAN_LORENZO: { code: '05', label: 'San Lorenzo' },
    ATACAMES: { code: '06', label: 'Atacames' },
    RIOVERDE: { code: '07', label: 'Rioverde' },
  },
  GUAYAS: {
    GUAYAQUIL: { code: '01', label: 'Guayaquil' },
    ALFREDO_BAQUERIZO_MORENO_JUJAN: {
      code: '02',
      label: 'Alfredo Baquerizo Moreno (Jujan)',
    },
    BALAO: { code: '03', label: 'Balao' },
    BALZAR: { code: '04', label: 'Balzar' },
    COLIMES: { code: '05', label: 'Colimes' },
    DAULE: { code: '06', label: 'Daule' },
    DURAN: { code: '07', label: 'Duran' },
    EL_EMPALME: { code: '08', label: 'El Empalme' },
    EL_TRIUNFO: { code: '09', label: 'El Triunfo' },
    MILAGRO: { code: '10', label: 'Milagro' },
    NARANJAL: { code: '11', label: 'Naranjal' },
    NARANJITO: { code: '12', label: 'Naranjito' },
    PALESTINA: { code: '13', label: 'Palestina' },
    PEDRO_CARBO: { code: '14', label: 'Pedro Carbo' },
    SALINAS: { code: '15', label: 'Salinas' },
    SANBORONDON: { code: '16', label: 'Sanborondón' },
    SANTA_ELENA: { code: '17', label: 'Santa Elena' },
    SANTA_LUCIA: { code: '18', label: 'Santa Lucía' },
    URBINA_JADO: { code: '19', label: 'Urbina Jado' },
    YAGUACHI: { code: '20', label: 'Yaguachi' },
    PLAYAS: { code: '21', label: 'Playas' },
    SIMON_BOLIVAR: { code: '22', label: 'Simón Bolívar' },
    CORONEL_MARCELINO_MARIDUENA: {
      code: '23',
      label: 'Coronel Marcelino Maridueña',
    },
    LOMAS_DE_SARGENTILLO: { code: '24', label: 'Lomas De Sargentillo' },
    NOBOL: { code: '25', label: 'Nobol' },
    LA_LIBERTAD: { code: '26', label: 'La Libertad' },
    GENERAL_ANTONIO_ELIZALDE: { code: '27', label: 'General Antonio Elizalde' },
    ISIDRO_AYORA: { code: '28', label: 'Isidro Ayora' },
    SALITRE: { code: '29', label: 'Salitre' },
  },
  IMBABURA: {
    IBARRA: { code: '01', label: 'Ibarra' },
    ANTONIO_ANTE: { code: '02', label: 'Antonio Ante' },
    COTACACHI: { code: '03', label: 'Cotacachi' },
    OTAVALO: { code: '04', label: 'Otavalo' },
    PIMAMPIRO: { code: '05', label: 'Pimampiro' },
    SAN_MIGUEL_DE_URCUQUI: { code: '06', label: 'San Miguel De Urcuquí' },
  },
  LOJA: {
    LOJA: { code: '01', label: 'Loja' },
    CALVAS: { code: '02', label: 'Calvas' },
    CATAMAYO: { code: '03', label: 'Catamayo' },
    CELICA: { code: '04', label: 'Celica' },
    CHAGUARPAMBA: { code: '05', label: 'Chaguarpamba' },
    ESPINDOLA: { code: '06', label: 'Espíndola' },
    GONZANAMA: { code: '07', label: 'Gonzanamá' },
    MACARA: { code: '08', label: 'Macará' },
    PALTAS: { code: '09', label: 'Paltas' },
    PUYANGO: { code: '10', label: 'Puyango' },
    SARAGURO: { code: '11', label: 'Saraguro' },
    SOZORANGA: { code: '12', label: 'Sozoranga' },
    ZAPOTILLO: { code: '13', label: 'Zapotillo' },
    PINDAL: { code: '14', label: 'Pindal' },
    QUILANGA: { code: '15', label: 'Quilanga' },
    OLMEDO: { code: '16', label: 'Olmedo' },
  },
  LOS_RIOS: {
    QUINSALOMA: { code: '13', label: 'Quinsaloma' },
    BABAHOYO: { code: '01', label: 'Babahoyo' },
    BABA: { code: '02', label: 'Baba' },
    MONTALVO: { code: '03', label: 'Montalvo' },
    PUEBLOVIEJO: { code: '04', label: 'Puebloviejo' },
    QUEVEDO: { code: '05', label: 'Quevedo' },
    URDANETA: { code: '06', label: 'Urdaneta' },
    VENTANAS: { code: '07', label: 'Ventanas' },
    VINCES: { code: '08', label: 'Vinces' },
    PALENQUE: { code: '09', label: 'Palenque' },
    BUENA_FE: { code: '10', label: 'Buena Fé' },
    VALENCIA: { code: '11', label: 'Valencia' },
    MOCACHE: { code: '12', label: 'Mocache' },
  },
  MANABI: {
    PORTOVIEJO: { code: '01', label: 'Portoviejo' },
    BOLIVAR: { code: '02', label: 'Bolívar' },
    CHONE: { code: '03', label: 'Chone' },
    EL_CARMEN: { code: '04', label: 'El Carmen' },
    FLAVIO_ALFARO: { code: '05', label: 'Flavio Alfaro' },
    JIPIJAPA: { code: '06', label: 'Jipijapa' },
    JUNIN: { code: '07', label: 'Junín' },
    MANTA: { code: '08', label: 'Manta' },
    MONTECRISTI: { code: '09', label: 'Montecristi' },
    PAJAN: { code: '10', label: 'Paján' },
    PICHINCHA: { code: '11', label: 'Pichincha' },
    ROCAFUERTE: { code: '12', label: 'Rocafuerte' },
    SANTA_ANA: { code: '13', label: 'Santa Ana' },
    SUCRE: { code: '14', label: 'Sucre' },
    TOSAGUA: { code: '15', label: 'Tosagua' },
    '24_DE_MAYO': { code: '16', label: '24 De Mayo' },
    PEDERNALES: { code: '17', label: 'Pedernales' },
    OLMEDO: { code: '18', label: 'Olmedo' },
    PUERTO_LOPEZ: { code: '19', label: 'Puerto López' },
    JAMA: { code: '20', label: 'Jama' },
    JARAMIJO: { code: '21', label: 'Jaramijó' },
    SAN_VICENTE: { code: '22', label: 'San Vicente' },
  },
  MORONA_SANTIAGO: {
    MORONA: { code: '01', label: 'Morona' },
    GUALAQUIZA: { code: '02', label: 'Gualaquiza' },
    LIMON_INDANZA: { code: '03', label: 'Limon-Indanza' },
    PALORA: { code: '04', label: 'Palora' },
    SANTIAGO: { code: '05', label: 'Santiago' },
    SUCUA: { code: '06', label: 'Sucúa' },
    HUAMBOYA: { code: '07', label: 'Huamboya' },
    SAN_JUAN_BOSCO: { code: '08', label: 'San Juan Bosco' },
    TAISHA: { code: '09', label: 'Taisha' },
    LOGRONO: { code: '10', label: 'Logroño' },
    PABLO_VI: { code: '11', label: 'Pablo Vi' },
    TIWINTZA: { code: '12', label: 'Tiwintza' },
  },
  NAPO: {
    TENA: { code: '01', label: 'Tena' },
    AGUARICO: { code: '02', label: 'Aguarico' },
    ARCHIDONA: { code: '03', label: 'Archidona' },
    EL_CHACO: { code: '04', label: 'El Chaco' },
    LA_JOYA_DE_LOS_SACHAS: { code: '05', label: 'La Joya De Los Sachas' },
    ORELLANA: { code: '06', label: 'Orellana' },
    QUIJOS: { code: '07', label: 'Quijos' },
    LORETO: { code: '08', label: 'Loreto' },
    CARLOS_JULIO_ARESEMENA_TOLA: {
      code: '09',
      label: 'Carlos Julio Aresemena Tola',
    },
  },
  PASTAZA: {
    PASTAZA: { code: '01', label: 'Pastaza' },
    MERA: { code: '02', label: 'Mera' },
    SANTA_CLARA: { code: '03', label: 'Santa Clara' },
    ARAJUNO: { code: '04', label: 'Arajuno' },
  },
  PICHINCHA: {
    QUITO: { code: '01', label: 'Quito' },
    CAYAMBE: { code: '02', label: 'Cayambe' },
    MEJIA: { code: '03', label: 'Mejía' },
    PEDRO_MONCAYO: { code: '04', label: 'Pedro Moncayo' },
    RUMINAHUI: { code: '05', label: 'Rumiñahui' },
    SANTO_DOMINGO: { code: '06', label: 'Santo Domingo' },
    SAN_MIGUEL_DE_LOS_BANCOS: { code: '07', label: 'San Miguel De Los Bancos' },
    PEDRO_VICENTE_MALDONADO: { code: '08', label: 'Pedro Vicente Maldonado' },
    PUERTO_QUITO: { code: '09', label: 'Puerto Quito' },
  },
  TUNGURAHUA: {
    AMBATO: { code: '01', label: 'Ambato' },
    BANOS: { code: '02', label: 'Baños' },
    CEVALLOS: { code: '03', label: 'Cevallos' },
    MOCHA: { code: '04', label: 'Mocha' },
    PATATE: { code: '05', label: 'Patate' },
    QUERO: { code: '06', label: 'Quero' },
    SAN_PEDRO_DE_PELILEO: { code: '07', label: 'San Pedro De Pelileo' },
    TISALEO: { code: '08', label: 'Tisaleo' },
    SANTIAGO_DE_PILLARO: { code: '09', label: 'Santiago De Píllaro' },
  },
  ZAMORA_CHINCHIPE: {
    ZAMORA: { code: '01', label: 'Zamora' },
    CHINCHIPE: { code: '02', label: 'Chinchipe' },
    NANGARITZA: { code: '03', label: 'Nangaritza' },
    YACUAMBI: { code: '04', label: 'Yacuambi' },
    YANTZAZA: { code: '05', label: 'Yantzaza' },
    EL_PANGUI: { code: '06', label: 'El Pangui' },
    CENTINELA_DEL_CONDOR: { code: '07', label: 'Centinela Del Cóndor' },
    PALANDA: { code: '08', label: 'Palanda' },
    PAQUISHA: { code: '09', label: 'Paquisha' },
  },
  GALAPAGOS: {
    SAN_CRISTOBAL: { code: '01', label: 'San Cristóbal' },
    ISABELA: { code: '02', label: 'Isabela' },
    SANTA_CRUZ: { code: '03', label: 'Santa Cruz' },
  },
  SUCUMBIOS: {
    LAGO_AGRIO: { code: '01', label: 'Lago Agrio' },
    GONZALO_PIZARRO: { code: '02', label: 'Gonzalo Pizarro' },
    PUTUMAYO: { code: '03', label: 'Putumayo' },
    SHUSHUFINDI: { code: '04', label: 'Shushufindi' },
    SUCUMBIOS: { code: '05', label: 'Sucumbios' },
    CASCALES: { code: '06', label: 'Cascales' },
    CUYABENO: { code: '07', label: 'Cuyabeno' },
  },
  ORELLANA: {
    ORELLANA: { code: '01', label: 'Orellana' },
    AGUARICO: { code: '02', label: 'Aguarico' },
    LA_JOYA_DE_LOS_SACHAS: { code: '03', label: 'La Joya De Los Sachas' },
    LORETO: { code: '04', label: 'Loreto' },
  },
  SANTO_DOMINGO_DE_LOS_TSACHILAS: {
    SANTO_DOMINGO: { code: '01', label: 'Santo Domingo' },
  },
  SANTA_ELENA: {
    LA_LIBERTAD: { code: '02', label: 'La Libertad' },
    SALINAS: { code: '03', label: 'Salinas' },
    SANTA_ELENA: { code: '01', label: 'Santa Elena' },
  },
  ZONAS_NO_DELIMITADAS: {
    LAS_GOLONDRINAS: { code: '01', label: 'Las Golondrinas' },
    MANGA_DEL_CURA: { code: '03', label: 'Manga Del Cura' },
    EL_PIEDRERO: { code: '04', label: 'El Piedrero' },
  },
} as const;

export function canton(parroquia_code: string, code: string) {
  const prov = provincia(parroquia_code);
  if (!prov) return undefined;

  const provCantones = cantones[prov.key] as Record<
    string,
    { code: string; label: string }
  >;
  if (!provCantones) return undefined;

  const entry = Object.entries(provCantones).find(([, v]) => v.code === code);
  if (!entry) return undefined;

  const [key, { label }] = entry;
  return { key, label };
}

export type Canton = Cantones[string][string];
