export enum NacionalidadCode {
  AFGHANISTAN = 'AFG',
  ALBANIA = 'ALB',
  ALGERIA = 'DZA',
  ANDORRA = 'AND',
  ANGOLA = 'AGO',
  ANTIGUA_AND_BARBUDA = 'ATG',
  ARGENTINA = 'ARG',
  ARMENIA = 'ARM',
  AUSTRALIA = 'AUS',
  AUSTRIA = 'AUT',
  AZERBAIJAN = 'AZE',
  BAHAMAS = 'BHS',
  BAHRAIN = 'BHR',
  BANGLADESH = 'BGD',
  BARBADOS = 'BRB',
  BELARUS = 'BLR',
  BELGIUM = 'BEL',
  BELIZE = 'BLZ',
  BENIN = 'BEN',
  BHUTAN = 'BTN',
  BOLIVIA = 'BOL',
  BOSNIA_AND_HERZEGOVINA = 'BIH',
  BOTSWANA = 'BWA',
  BRAZIL = 'BRA',
  BRUNEI = 'BRN',
  BULGARIA = 'BGR',
  BURKINA_FASO = 'BFA',
  BURUNDI = 'BDI',
  CABO_VERDE = 'CPV',
  CAMBODIA = 'KHM',
  CAMEROON = 'CMR',
  CANADA = 'CAN',
  CENTRAL_AFRICAN_REPUBLIC = 'CAF',
  CHAD = 'TCD',
  CHILE = 'CHL',
  CHINA = 'CHN',
  COLOMBIA = 'COL',
  COMOROS = 'COM',
  CONGO = 'COG',
  CONGO_DRC = 'COD',
  COSTA_RICA = 'CRI',
  COTE_DIVOIRE = 'CIV',
  CROATIA = 'HRV',
  CUBA = 'CUB',
  CYPRUS = 'CYP',
  CZECH_REPUBLIC = 'CZE',
  DENMARK = 'DNK',
  DJIBOUTI = 'DJI',
  DOMINICA = 'DMA',
  DOMINICAN_REPUBLIC = 'DOM',
  ECUADOR = 'ECU',
  EGYPT = 'EGY',
  EL_SALVADOR = 'SLV',
  EQUATORIAL_GUINEA = 'GNQ',
  ERITREA = 'ERI',
  ESTONIA = 'EST',
  ESWATINI = 'SWZ',
  ETHIOPIA = 'ETH',
  FIJI = 'FJI',
  FINLAND = 'FIN',
  FRANCE = 'FRA',
  GABON = 'GAB',
  GAMBIA = 'GMB',
  GEORGIA = 'GEO',
  GERMANY = 'DEU',
  GHANA = 'GHA',
  GREECE = 'GRC',
  GRENADA = 'GRD',
  GUATEMALA = 'GTM',
  GUINEA = 'GIN',
  GUINEA_BISSAU = 'GNB',
  GUYANA = 'GUY',
  HAITI = 'HTI',
  HONDURAS = 'HND',
  HUNGARY = 'HUN',
  ICELAND = 'ISL',
  INDIA = 'IND',
  INDONESIA = 'IDN',
  IRAN = 'IRN',
  IRAQ = 'IRQ',
  IRELAND = 'IRL',
  ISRAEL = 'ISR',
  ITALY = 'ITA',
  JAMAICA = 'JAM',
  JAPAN = 'JPN',
  JORDAN = 'JOR',
  KAZAKHSTAN = 'KAZ',
  KENYA = 'KEN',
  KIRIBATI = 'KIR',
  KOREA_NORTH = 'PRK',
  KOREA_SOUTH = 'KOR',
  KUWAIT = 'KWT',
  KYRGYZSTAN = 'KGZ',
  LAOS = 'LAO',
  LATVIA = 'LVA',
  LEBANON = 'LBN',
  LESOTHO = 'LSO',
  LIBERIA = 'LBR',
  LIBYA = 'LBY',
  LIECHTENSTEIN = 'LIE',
  LITHUANIA = 'LTU',
  LUXEMBOURG = 'LUX',
  MADAGASCAR = 'MDG',
  MALAWI = 'MWI',
  MALAYSIA = 'MYS',
  MALDIVES = 'MDV',
  MALI = 'MLI',
  MALTA = 'MLT',
  MARSHALL_ISLANDS = 'MHL',
  MAURITANIA = 'MRT',
  MAURITIUS = 'MUS',
  MEXICO = 'MEX',
  MICRONESIA = 'FSM',
  MOLDOVA = 'MDA',
  MONACO = 'MCO',
  MONGOLIA = 'MNG',
  MONTENEGRO = 'MNE',
  MOROCCO = 'MAR',
  MOZAMBIQUE = 'MOZ',
  MYANMAR = 'MMR',
  NAMIBIA = 'NAM',
  NAURU = 'NRU',
  NEPAL = 'NPL',
  NETHERLANDS = 'NLD',
  NEW_ZEALAND = 'NZL',
  NICARAGUA = 'NIC',
  NIGER = 'NER',
  NIGERIA = 'NGA',
  NORTH_MACEDONIA = 'MKD',
  NORWAY = 'NOR',
  OMAN = 'OMN',
  PAKISTAN = 'PAK',
  PALAU = 'PLW',
  PALESTINE = 'PSE',
  PANAMA = 'PAN',
  PAPUA_NEW_GUINEA = 'PNG',
  PARAGUAY = 'PRY',
  PERU = 'PER',
  PHILIPPINES = 'PHL',
  POLAND = 'POL',
  PORTUGAL = 'PRT',
  QATAR = 'QAT',
  ROMANIA = 'ROU',
  RUSSIA = 'RUS',
  RWANDA = 'RWA',
  SAINT_KITTS_AND_NEVIS = 'KNA',
  SAINT_LUCIA = 'LCA',
  SAINT_VINCENT_AND_THE_GRENADINES = 'VCT',
  SAMOA = 'WSM',
  SAN_MARINO = 'SMR',
  SAO_TOME_AND_PRINCIPE = 'STP',
  SAUDI_ARABIA = 'SAU',
  SENEGAL = 'SEN',
  SERBIA = 'SRB',
  SEYCHELLES = 'SYC',
  SIERRA_LEONE = 'SLE',
  SINGAPORE = 'SGP',
  SLOVAKIA = 'SVK',
  SLOVENIA = 'SVN',
  SOLOMON_ISLANDS = 'SLB',
  SOMALIA = 'SOM',
  SOUTH_AFRICA = 'ZAF',
  SOUTH_SUDAN = 'SSD',
  SPAIN = 'ESP',
  SRI_LANKA = 'LKA',
  SUDAN = 'SDN',
  SURINAME = 'SUR',
  SWEDEN = 'SWE',
  SWITZERLAND = 'CHE',
  SYRIA = 'SYR',
  TAIWAN = 'TWN',
  TAJIKISTAN = 'TJK',
  TANZANIA = 'TZA',
  THAILAND = 'THA',
  TIMOR_LESTE = 'TLS',
  TOGO = 'TGO',
  TONGA = 'TON',
  TRINIDAD_AND_TOBAGO = 'TTO',
  TUNISIA = 'TUN',
  TURKEY = 'TUR',
  TURKMENISTAN = 'TKM',
  TUVALU = 'TUV',
  UGANDA = 'UGA',
  UKRAINE = 'UKR',
  UNITED_ARAB_EMIRATES = 'ARE',
  UNITED_KINGDOM = 'GBR',
  UNITED_STATES = 'USA',
  URUGUAY = 'URY',
  UZBEKISTAN = 'UZB',
  VANUATU = 'VUT',
  VATICAN_CITY = 'VAT',
  VENEZUELA = 'VEN',
  VIETNAM = 'VNM',
  YEMEN = 'YEM',
  ZAMBIA = 'ZMB',
  ZIMBABWE = 'ZWE',
}

export const NacionalidadCodeLabel: Record<NacionalidadCode, string> = {
  [NacionalidadCode.AFGHANISTAN]: 'Afganistán',
  [NacionalidadCode.ALBANIA]: 'Albania',
  [NacionalidadCode.ALGERIA]: 'Argelia',
  [NacionalidadCode.ANDORRA]: 'Andorra',
  [NacionalidadCode.ANGOLA]: 'Angola',
  [NacionalidadCode.ANTIGUA_AND_BARBUDA]: 'Antigua y Barbuda',
  [NacionalidadCode.ARGENTINA]: 'Argentina',
  [NacionalidadCode.ARMENIA]: 'Armenia',
  [NacionalidadCode.AUSTRALIA]: 'Australia',
  [NacionalidadCode.AUSTRIA]: 'Austria',
  [NacionalidadCode.AZERBAIJAN]: 'Azerbaiyán',
  [NacionalidadCode.BAHAMAS]: 'Bahamas',
  [NacionalidadCode.BAHRAIN]: 'Baréin',
  [NacionalidadCode.BANGLADESH]: 'Bangladesh',
  [NacionalidadCode.BARBADOS]: 'Barbados',
  [NacionalidadCode.BELARUS]: 'Bielorrusia',
  [NacionalidadCode.BELGIUM]: 'Bélgica',
  [NacionalidadCode.BELIZE]: 'Belice',
  [NacionalidadCode.BENIN]: 'Benín',
  [NacionalidadCode.BHUTAN]: 'Bután',
  [NacionalidadCode.BOLIVIA]: 'Bolivia',
  [NacionalidadCode.BOSNIA_AND_HERZEGOVINA]: 'Bosnia y Herzegovina',
  [NacionalidadCode.BOTSWANA]: 'Botsuana',
  [NacionalidadCode.BRAZIL]: 'Brasil',
  [NacionalidadCode.BRUNEI]: 'Brunéi Darussalam',
  [NacionalidadCode.BULGARIA]: 'Bulgaria',
  [NacionalidadCode.BURKINA_FASO]: 'Burkina Faso',
  [NacionalidadCode.BURUNDI]: 'Burundi',
  [NacionalidadCode.CABO_VERDE]: 'Cabo Verde',
  [NacionalidadCode.CAMBODIA]: 'Camboya',
  [NacionalidadCode.CAMEROON]: 'Camerún',
  [NacionalidadCode.CANADA]: 'Canadá',
  [NacionalidadCode.CENTRAL_AFRICAN_REPUBLIC]: 'República Centroafricana',
  [NacionalidadCode.CHAD]: 'Chad',
  [NacionalidadCode.CHILE]: 'Chile',
  [NacionalidadCode.CHINA]: 'China',
  [NacionalidadCode.COLOMBIA]: 'Colombia',
  [NacionalidadCode.COMOROS]: 'Comoras',
  [NacionalidadCode.CONGO]: 'Congo',
  [NacionalidadCode.CONGO_DRC]: 'República Democrática del Congo',
  [NacionalidadCode.COSTA_RICA]: 'Costa Rica',
  [NacionalidadCode.COTE_DIVOIRE]: 'Costa de Marfil',
  [NacionalidadCode.CROATIA]: 'Croacia',
  [NacionalidadCode.CUBA]: 'Cuba',
  [NacionalidadCode.CYPRUS]: 'Chipre',
  [NacionalidadCode.CZECH_REPUBLIC]: 'República Checa',
  [NacionalidadCode.DENMARK]: 'Dinamarca',
  [NacionalidadCode.DJIBOUTI]: 'Yibuti',
  [NacionalidadCode.DOMINICA]: 'Dominica',
  [NacionalidadCode.DOMINICAN_REPUBLIC]: 'República Dominicana',
  [NacionalidadCode.ECUADOR]: 'Ecuador',
  [NacionalidadCode.EGYPT]: 'Egipto',
  [NacionalidadCode.EL_SALVADOR]: 'El Salvador',
  [NacionalidadCode.EQUATORIAL_GUINEA]: 'Guinea Ecuatorial',
  [NacionalidadCode.ERITREA]: 'Eritrea',
  [NacionalidadCode.ESTONIA]: 'Estonia',
  [NacionalidadCode.ESWATINI]: 'Esuatini',
  [NacionalidadCode.ETHIOPIA]: 'Etiopía',
  [NacionalidadCode.FIJI]: 'Fiyi',
  [NacionalidadCode.FINLAND]: 'Finlandia',
  [NacionalidadCode.FRANCE]: 'Francia',
  [NacionalidadCode.GABON]: 'Gabón',
  [NacionalidadCode.GAMBIA]: 'Gambia',
  [NacionalidadCode.GEORGIA]: 'Georgia',
  [NacionalidadCode.GERMANY]: 'Alemania',
  [NacionalidadCode.GHANA]: 'Ghana',
  [NacionalidadCode.GREECE]: 'Grecia',
  [NacionalidadCode.GRENADA]: 'Granada',
  [NacionalidadCode.GUATEMALA]: 'Guatemala',
  [NacionalidadCode.GUINEA]: 'Guinea',
  [NacionalidadCode.GUINEA_BISSAU]: 'Guinea-Bisáu',
  [NacionalidadCode.GUYANA]: 'Guyana',
  [NacionalidadCode.HAITI]: 'Haití',
  [NacionalidadCode.HONDURAS]: 'Honduras',
  [NacionalidadCode.HUNGARY]: 'Hungría',
  [NacionalidadCode.ICELAND]: 'Islandia',
  [NacionalidadCode.INDIA]: 'India',
  [NacionalidadCode.INDONESIA]: 'Indonesia',
  [NacionalidadCode.IRAN]: 'Irán',
  [NacionalidadCode.IRAQ]: 'Iraq',
  [NacionalidadCode.IRELAND]: 'Irlanda',
  [NacionalidadCode.ISRAEL]: 'Israel',
  [NacionalidadCode.ITALY]: 'Italia',
  [NacionalidadCode.JAMAICA]: 'Jamaica',
  [NacionalidadCode.JAPAN]: 'Japón',
  [NacionalidadCode.JORDAN]: 'Jordania',
  [NacionalidadCode.KAZAKHSTAN]: 'Kazajistán',
  [NacionalidadCode.KENYA]: 'Kenia',
  [NacionalidadCode.KIRIBATI]: 'Kiribati',
  [NacionalidadCode.KOREA_NORTH]: 'Corea del Norte',
  [NacionalidadCode.KOREA_SOUTH]: 'Corea del Sur',
  [NacionalidadCode.KUWAIT]: 'Kuwait',
  [NacionalidadCode.KYRGYZSTAN]: 'Kirguistán',
  [NacionalidadCode.LAOS]: 'Laos',
  [NacionalidadCode.LATVIA]: 'Letonia',
  [NacionalidadCode.LEBANON]: 'Líbano',
  [NacionalidadCode.LESOTHO]: 'Lesoto',
  [NacionalidadCode.LIBERIA]: 'Liberia',
  [NacionalidadCode.LIBYA]: 'Libia',
  [NacionalidadCode.LIECHTENSTEIN]: 'Liechtenstein',
  [NacionalidadCode.LITHUANIA]: 'Lituania',
  [NacionalidadCode.LUXEMBOURG]: 'Luxemburgo',
  [NacionalidadCode.MADAGASCAR]: 'Madagascar',
  [NacionalidadCode.MALAWI]: 'Malaui',
  [NacionalidadCode.MALAYSIA]: 'Malasia',
  [NacionalidadCode.MALDIVES]: 'Maldivas',
  [NacionalidadCode.MALI]: 'Malí',
  [NacionalidadCode.MALTA]: 'Malta',
  [NacionalidadCode.MARSHALL_ISLANDS]: 'Islas Marshall',
  [NacionalidadCode.MAURITANIA]: 'Mauritania',
  [NacionalidadCode.MAURITIUS]: 'Mauricio',
  [NacionalidadCode.MEXICO]: 'México',
  [NacionalidadCode.MICRONESIA]: 'Micronesia',
  [NacionalidadCode.MOLDOVA]: 'Moldavia',
  [NacionalidadCode.MONACO]: 'Mónaco',
  [NacionalidadCode.MONGOLIA]: 'Mongolia',
  [NacionalidadCode.MONTENEGRO]: 'Montenegro',
  [NacionalidadCode.MOROCCO]: 'Marruecos',
  [NacionalidadCode.MOZAMBIQUE]: 'Mozambique',
  [NacionalidadCode.MYANMAR]: 'Myanmar',
  [NacionalidadCode.NAMIBIA]: 'Namibia',
  [NacionalidadCode.NAURU]: 'Nauru',
  [NacionalidadCode.NEPAL]: 'Nepal',
  [NacionalidadCode.NETHERLANDS]: 'Países Bajos',
  [NacionalidadCode.NEW_ZEALAND]: 'Nueva Zelanda',
  [NacionalidadCode.NICARAGUA]: 'Nicaragua',
  [NacionalidadCode.NIGER]: 'Níger',
  [NacionalidadCode.NIGERIA]: 'Nigeria',
  [NacionalidadCode.NORTH_MACEDONIA]: 'Macedonia del Norte',
  [NacionalidadCode.NORWAY]: 'Noruega',
  [NacionalidadCode.OMAN]: 'Omán',
  [NacionalidadCode.PAKISTAN]: 'Pakistán',
  [NacionalidadCode.PALAU]: 'Palaos',
  [NacionalidadCode.PALESTINE]: 'Palestina',
  [NacionalidadCode.PANAMA]: 'Panamá',
  [NacionalidadCode.PAPUA_NEW_GUINEA]: 'Papúa Nueva Guinea',
  [NacionalidadCode.PARAGUAY]: 'Paraguay',
  [NacionalidadCode.PERU]: 'Perú',
  [NacionalidadCode.PHILIPPINES]: 'Filipinas',
  [NacionalidadCode.POLAND]: 'Polonia',
  [NacionalidadCode.PORTUGAL]: 'Portugal',
  [NacionalidadCode.QATAR]: 'Catar',
  [NacionalidadCode.ROMANIA]: 'Rumania',
  [NacionalidadCode.RUSSIA]: 'Rusia',
  [NacionalidadCode.RWANDA]: 'Ruanda',
  [NacionalidadCode.SAINT_KITTS_AND_NEVIS]: 'San Cristóbal y Nieves',
  [NacionalidadCode.SAINT_LUCIA]: 'Santa Lucía',
  [NacionalidadCode.SAINT_VINCENT_AND_THE_GRENADINES]:
    'San Vicente y las Granadinas',
  [NacionalidadCode.SAMOA]: 'Samoa',
  [NacionalidadCode.SAN_MARINO]: 'San Marino',
  [NacionalidadCode.SAO_TOME_AND_PRINCIPE]: 'Santo Tomé y Príncipe',
  [NacionalidadCode.SAUDI_ARABIA]: 'Arabia Saudí',
  [NacionalidadCode.SENEGAL]: 'Senegal',
  [NacionalidadCode.SERBIA]: 'Serbia',
  [NacionalidadCode.SEYCHELLES]: 'Seychelles',
  [NacionalidadCode.SIERRA_LEONE]: 'Sierra Leona',
  [NacionalidadCode.SINGAPORE]: 'Singapur',
  [NacionalidadCode.SLOVAKIA]: 'Eslovaquia',
  [NacionalidadCode.SLOVENIA]: 'Eslovenia',
  [NacionalidadCode.SOLOMON_ISLANDS]: 'Islas Salomón',
  [NacionalidadCode.SOMALIA]: 'Somalia',
  [NacionalidadCode.SOUTH_AFRICA]: 'Sudáfrica',
  [NacionalidadCode.SOUTH_SUDAN]: 'Sudán del Sur',
  [NacionalidadCode.SPAIN]: 'España',
  [NacionalidadCode.SRI_LANKA]: 'Sri Lanka',
  [NacionalidadCode.SUDAN]: 'Sudán',
  [NacionalidadCode.SURINAME]: 'Surinam',
  [NacionalidadCode.SWEDEN]: 'Suecia',
  [NacionalidadCode.SWITZERLAND]: 'Suiza',
  [NacionalidadCode.SYRIA]: 'Siria',
  [NacionalidadCode.TAIWAN]: 'Taiwán',
  [NacionalidadCode.TAJIKISTAN]: 'Tayikistán',
  [NacionalidadCode.TANZANIA]: 'Tanzania',
  [NacionalidadCode.THAILAND]: 'Tailandia',
  [NacionalidadCode.TIMOR_LESTE]: 'Timor Oriental',
  [NacionalidadCode.TOGO]: 'Togo',
  [NacionalidadCode.TONGA]: 'Tonga',
  [NacionalidadCode.TRINIDAD_AND_TOBAGO]: 'Trinidad y Tobago',
  [NacionalidadCode.TUNISIA]: 'Túnez',
  [NacionalidadCode.TURKEY]: 'Turquía',
  [NacionalidadCode.TURKMENISTAN]: 'Turkmenistán',
  [NacionalidadCode.TUVALU]: 'Tuvalu',
  [NacionalidadCode.UGANDA]: 'Uganda',
  [NacionalidadCode.UKRAINE]: 'Ucrania',
  [NacionalidadCode.UNITED_ARAB_EMIRATES]: 'Emiratos Árabes Unidos',
  [NacionalidadCode.UNITED_KINGDOM]: 'Reino Unido',
  [NacionalidadCode.UNITED_STATES]: 'Estados Unidos',
  [NacionalidadCode.URUGUAY]: 'Uruguay',
  [NacionalidadCode.UZBEKISTAN]: 'Uzbekistán',
  [NacionalidadCode.VANUATU]: 'Vanuatu',
  [NacionalidadCode.VATICAN_CITY]: 'Ciudad del Vaticano',
  [NacionalidadCode.VENEZUELA]: 'Venezuela',
  [NacionalidadCode.VIETNAM]: 'Vietnam',
  [NacionalidadCode.YEMEN]: 'Yemen',
  [NacionalidadCode.ZAMBIA]: 'Zambia',
  [NacionalidadCode.ZIMBABWE]: 'Zimbabue',
} as const;

export enum NacionalidadUsoCode {
  NACIMIENTO = 'NAC',
  RESIDENCIA = 'RES',
}
export const NacionalidadUsoCodeLabel: Record<NacionalidadUsoCode, string> = {
  [NacionalidadUsoCode.NACIMIENTO]: 'País de nacimiento',
  [NacionalidadUsoCode.RESIDENCIA]: 'País de residencia',
} as const;
