import type { CodeOf } from '../helper/labelByCode';
import { labelOf } from '../helper/labelByCode';

const ETNIA = {
  MESTIZO: { code: 'MEST', label: 'Mestizo' },
  MONTUBIO: { code: 'MON', label: 'Montubio' },
  INDIGENA: { code: 'IND', label: 'Indígena' },
  AFRODESCENDIENTE: { code: 'AFRO', label: 'Afrodescendiente' },
  BLANCO: { code: 'BLAN', label: 'Blanco' },
  ASIATICO: { code: 'ASI', label: 'Asiático' },
  OTRO: { code: 'OTRO', label: 'Otro' },
} as const;
export type Etnia = CodeOf<typeof ETNIA>;
export const EtniaLabel = labelOf(ETNIA);

const NACIONALIDAD = {
  AFGHANISTAN: { code: 'AFG', label: 'Afganistán' },
  ALBANIA: { code: 'ALB', label: 'Albania' },
  ALGERIA: { code: 'DZA', label: 'Argelia' },
  ANDORRA: { code: 'AND', label: 'Andorra' },
  ANGOLA: { code: 'AGO', label: 'Angola' },
  ANTIGUA_AND_BARBUDA: { code: 'ATG', label: 'Antigua y Barbuda' },
  ARGENTINA: { code: 'ARG', label: 'Argentina' },
  ARMENIA: { code: 'ARM', label: 'Armenia' },
  AUSTRALIA: { code: 'AUS', label: 'Australia' },
  AUSTRIA: { code: 'AUT', label: 'Austria' },
  AZERBAIJAN: { code: 'AZE', label: 'Azerbaiyán' },
  BAHAMAS: { code: 'BHS', label: 'Bahamas' },
  BAHRAIN: { code: 'BHR', label: 'Bahréin' },
  BANGLADESH: { code: 'BGD', label: 'Bangladés' },
  BARBADOS: { code: 'BRB', label: 'Barbados' },
  BELARUS: { code: 'BLR', label: 'Bielorrusia' },
  BELGIUM: { code: 'BEL', label: 'Bélgica' },
  BELIZE: { code: 'BLZ', label: 'Belice' },
  BENIN: { code: 'BEN', label: 'Benín' },
  BHUTAN: { code: 'BTN', label: 'Bután' },
  BOLIVIA: { code: 'BOL', label: 'Bolivia' },
  BOSNIA_AND_HERZEGOVINA: { code: 'BIH', label: 'Bosnia y Herzegovina' },
  BOTSWANA: { code: 'BWA', label: 'Botsuana' },
  BRAZIL: { code: 'BRA', label: 'Brasil' },
  BRUNEI: { code: 'BRN', label: 'Brunéi' },
  BULGARIA: { code: 'BGR', label: 'Bulgaria' },
  BURKINA_FASO: { code: 'BFA', label: 'Burkina Faso' },
  BURUNDI: { code: 'BDI', label: 'Burundi' },
  CABO_VERDE: { code: 'CPV', label: 'Cabo Verde' },
  CAMBODIA: { code: 'KHM', label: 'Camboya' },
  CAMEROON: { code: 'CMR', label: 'Camerún' },
  CANADA: { code: 'CAN', label: 'Canadá' },
  CENTRAL_AFRICAN_REPUBLIC: { code: 'CAF', label: 'República Centroafricana' },
  CHAD: { code: 'TCD', label: 'Chad' },
  CHILE: { code: 'CHL', label: 'Chile' },
  CHINA: { code: 'CHN', label: 'China' },
  COLOMBIA: { code: 'COL', label: 'Colombia' },
  COMOROS: { code: 'COM', label: 'Comoras' },
  CONGO: { code: 'COG', label: 'Congo' },
  CONGO_DRC: { code: 'COD', label: 'Congo, República Democrática del' },
  COSTA_RICA: { code: 'CRI', label: 'Costa Rica' },
  COTE_DIVOIRE: { code: 'CIV', label: 'Costa de Marfil' },
  CROATIA: { code: 'HRV', label: 'Croacia' },
  CUBA: { code: 'CUB', label: 'Cuba' },
  CYPRUS: { code: 'CYP', label: 'Chipre' },
  CZECH_REPUBLIC: { code: 'CZE', label: 'República Checa' },
  DENMARK: { code: 'DNK', label: 'Dinamarca' },
  DJIBOUTI: { code: 'DJI', label: 'Yibuti' },
  DOMINICA: { code: 'DMA', label: 'Dominica' },
  DOMINICAN_REPUBLIC: { code: 'DOM', label: 'República Dominicana' },
  ECUADOR: { code: 'ECU', label: 'Ecuador' },
  EGYPT: { code: 'EGY', label: 'Egipto' },
  EL_SALVADOR: { code: 'SLV', label: 'El Salvador' },
  EQUATORIAL_GUINEA: { code: 'GNQ', label: 'Guinea Ecuatorial' },
  ERITREA: { code: 'ERI', label: 'Eritrea' },
  ESTONIA: { code: 'EST', label: 'Estonia' },
  ESWATINI: { code: 'SWZ', label: 'Eswatini' },
  ETHIOPIA: { code: 'ETH', label: 'Etiopía' },
  FIJI: { code: 'FJI', label: 'Fiyi' },
  FINLAND: { code: 'FIN', label: 'Finlandia' },
  FRANCE: { code: 'FRA', label: 'Francia' },
  GABON: { code: 'GAB', label: 'Gabon' },
  GAMBIA: { code: 'GMB', label: 'Gambia' },
  GEORGIA: { code: 'GEO', label: 'Georgia' },
  GERMANY: { code: 'DEU', label: 'Alemania' },
  GHANA: { code: 'GHA', label: 'Ghana' },
  GREECE: { code: 'GRC', label: 'Grecia' },
  GRENADA: { code: 'GRD', label: 'Granada' },
  GUATEMALA: { code: 'GTM', label: 'Guatemala' },
  GUINEA: { code: 'GIN', label: 'Guinea' },
  GUINEA_BISSAU: { code: 'GNB', label: 'Guinea-Bisáu' },
  GUYANA: { code: 'GUY', label: 'Guyana' },
  HAITI: { code: 'HTI', label: 'Haití' },
  HONDURAS: { code: 'HND', label: 'Honduras' },
  HUNGARY: { code: 'HUN', label: 'Hungría' },
  ICELAND: { code: 'ISL', label: 'Islandia' },
  INDIA: { code: 'IND', label: 'India' },
  INDONESIA: { code: 'IDN', label: 'Indonesia' },
  IRAN: { code: 'IRN', label: 'Irán' },
  IRAQ: { code: 'IRQ', label: 'Irak' },
  IRELAND: { code: 'IRL', label: 'Irlanda' },
  ISRAEL: { code: 'ISR', label: 'Israel' },
  ITALY: { code: 'ITA', label: 'Italia' },
  JAMAICA: { code: 'JAM', label: 'Jamaica' },
  JAPAN: { code: 'JPN', label: 'Japón' },
  JORDAN: { code: 'JOR', label: 'Jordania' },
  KAZAKHSTAN: { code: 'KAZ', label: 'Kazajistán' },
  KENYA: { code: 'KEN', label: 'Kenia' },
  KIRIBATI: { code: 'KIR', label: 'Kiribati' },
  KOREA_NORTH: { code: 'PRK', label: 'Corea del Norte' },
  KOREA_SOUTH: { code: 'KOR', label: 'Corea del Sur' },
  KUWAIT: { code: 'KWT', label: 'Kuwait' },
  KYRGYZSTAN: { code: 'KGZ', label: 'Kirguistán' },
  LAOS: { code: 'LAO', label: 'Laos' },
  LATVIA: { code: 'LVA', label: 'Letonia' },
  LEBANON: { code: 'LBN', label: 'Líbano' },
  LESOTHO: { code: 'LSO', label: 'Lesoto' },
  LIBERIA: { code: 'LBR', label: 'Liberia' },
  LIBYA: { code: 'LBY', label: 'Libia' },
  LIECHTENSTEIN: { code: 'LIE', label: 'Liechtenstein' },
  LITHUANIA: { code: 'LTU', label: 'Lituania' },
  LUXEMBOURG: { code: 'LUX', label: 'Luxemburgo' },
  MADAGASCAR: { code: 'MDG', label: 'Madagascar' },
  MALAWI: { code: 'MWI', label: 'Malawi' },
  MALAYSIA: { code: 'MYS', label: 'Malasia' },
  MALDIVES: { code: 'MDV', label: 'Maldivas' },
  MALI: { code: 'MLI', label: 'Mali' },
  MALTA: { code: 'MLT', label: 'Malta' },
  MARSHALL_ISLANDS: { code: 'MHL', label: 'Islas Marshall' },
  MAURITANIA: { code: 'MRT', label: 'Mauritania' },
  MAURITIUS: { code: 'MUS', label: 'Mauricio' },
  MEXICO: { code: 'MEX', label: 'México' },
  MICRONESIA: { code: 'FSM', label: 'Micronesia' },
  MOLDOVA: { code: 'MDA', label: 'Moldavia' },
  MONACO: { code: 'MCO', label: 'Mónaco' },
  MONGOLIA: { code: 'MNG', label: 'Mongolia' },
  MONTENEGRO: { code: 'MNE', label: 'Montenegro' },
  MOROCCO: { code: 'MAR', label: 'Marruecos' },
  MOZAMBIQUE: { code: 'MOZ', label: 'Mozambique' },
  MYANMAR: { code: 'MMR', label: 'Birmania' },
  NAMIBIA: { code: 'NAM', label: 'Namibia' },
  NAURU: { code: 'NRU', label: 'Nauru' },
  NEPAL: { code: 'NPL', label: 'Nepal' },
  NETHERLANDS: { code: 'NLD', label: 'Países Bajos' },
  NEW_ZEALAND: { code: 'NZL', label: 'Nueva Zelanda' },
  NICARAGUA: { code: 'NIC', label: 'Nicaragua' },
  NIGER: { code: 'NER', label: 'Niger' },
  NIGERIA: { code: 'NGA', label: 'Nigeria' },
  NORTH_MACEDONIA: { code: 'MKD', label: 'Macedonia del Norte' },
  NORWAY: { code: 'NOR', label: 'Noruega' },
  OMAN: { code: 'OMN', label: 'Omán' },
  PAKISTAN: { code: 'PAK', label: 'Pakistán' },
  PALAU: { code: 'PLW', label: 'Palau' },
  PALESTINE: { code: 'PSE', label: 'Palestina' },
  PANAMA: { code: 'PAN', label: 'Panamá' },
  PAPUA_NEW_GUINEA: { code: 'PNG', label: 'Papúa Nueva Guinea' },
  PARAGUAY: { code: 'PRY', label: 'Paraguay' },
  PERU: { code: 'PER', label: 'Perú' },
  PHILIPPINES: { code: 'PHL', label: 'Filipinas' },
  POLAND: { code: 'POL', label: 'Polonia' },
  PORTUGAL: { code: 'PRT', label: 'Portugal' },
  QATAR: { code: 'QAT', label: 'Catar' },
  ROMANIA: { code: 'ROU', label: 'Rumania' },
  RUSSIA: { code: 'RUS', label: 'Rusia' },
  RWANDA: { code: 'RWA', label: 'Ruanda' },
  SAINT_KITTS_AND_NEVIS: { code: 'KNA', label: 'San Cristóbal y Nieves' },
  SAINT_LUCIA: { code: 'LCA', label: 'Santa Lucía' },
  SAINT_VINCENT_AND_THE_GRENADINES: {
    code: 'VCT',
    label: 'San Vicente y las Granadinas',
  },
  SAMOA: { code: 'WSM', label: 'Samoa' },
  SAN_MARINO: { code: 'SMR', label: 'San Marino' },
  SAO_TOME_AND_PRINCIPE: { code: 'STP', label: 'Santo Tomé y Príncipe' },
  SAUDI_ARABIA: { code: 'SAU', label: 'Arabia Saudita' },
  SENEGAL: { code: 'SEN', label: 'Senegal' },
  SERBIA: { code: 'SRB', label: 'Serbia' },
  SEYCHELLES: { code: 'SYC', label: 'Seychelles' },
  SIERRA_LEONE: { code: 'SLE', label: 'Sierra Leona' },
  SINGAPORE: { code: 'SGP', label: 'Singapur' },
  SLOVAKIA: { code: 'SVK', label: 'Eslovaquia' },
  SLOVENIA: { code: 'SVN', label: 'Eslovenia' },
  SOLOMON_ISLANDS: { code: 'SLB', label: 'Islas Salomón' },
  SOMALIA: { code: 'SOM', label: 'Somalia' },
  SOUTH_AFRICA: { code: 'ZAF', label: 'Sudáfrica' },
  SOUTH_SUDAN: { code: 'SSD', label: 'Sudán del Sur' },
  SPAIN: { code: 'ESP', label: 'España' },
  SRI_LANKA: { code: 'LKA', label: 'Sri Lanka' },
  SUDAN: { code: 'SDN', label: 'Sudán' },
  SURINAME: { code: 'SUR', label: 'Surinam' },
  SWEDEN: { code: 'SWE', label: 'Suecia' },
  SWITZERLAND: { code: 'CHE', label: 'Suiza' },
  SYRIA: { code: 'SYR', label: 'Siria' },
  TAIWAN: { code: 'TWN', label: 'Taiwán' },
  TAJIKISTAN: { code: 'TJK', label: 'Tayikistán' },
  TANZANIA: { code: 'TZA', label: 'Tanzania' },
  THAILAND: { code: 'THA', label: 'Tailandia' },
  TIMOR_LESTE: { code: 'TLS', label: 'Timor Oriental' },
  TOGO: { code: 'TGO', label: 'Togo' },
  TONGA: { code: 'TON', label: 'Tonga' },
  TRINIDAD_AND_TOBAGO: { code: 'TTO', label: 'Trinidad y Tobago' },
  TUNISIA: { code: 'TUN', label: 'Túnez' },
  TURKEY: { code: 'TUR', label: 'Turquía' },
  TURKMENISTAN: { code: 'TKM', label: 'Turkmenistán' },
  TUVALU: { code: 'TUV', label: 'Tuvalu' },
  UGANDA: { code: 'UGA', label: 'Uganda' },
  UKRAINE: { code: 'UKR', label: 'Ucrania' },
  UNITED_ARAB_EMIRATES: { code: 'ARE', label: 'Emiratos Árabes Unidos' },
  UNITED_KINGDOM: { code: 'GBR', label: 'Reino Unido' },
  UNITED_STATES: { code: 'USA', label: 'Estados Unidos' },
  URUGUAY: { code: 'URY', label: 'Uruguay' },
  UZBEKISTAN: { code: 'UZB', label: 'Uzbekistán' },
  VANUATU: { code: 'VUT', label: 'Vanuatu' },
  VATICAN_CITY: { code: 'VAT', label: 'Vaticano' },
  VENEZUELA: { code: 'VEN', label: 'Venezuela' },
  VIETNAM: { code: 'VNM', label: 'Vietnam' },
  YEMEN: { code: 'YEM', label: 'Yemen' },
  ZAMBIA: { code: 'ZMB', label: 'Zambia' },
  ZIMBABWE: { code: 'ZWE', label: 'Zimbabue' },
} as const;
export type Nacionalidad = CodeOf<typeof NACIONALIDAD>;
export const NacionalidadLabel = labelOf(NACIONALIDAD);

const USO_NACIONALIDAD = {
  NACIMIENTO: { code: 'NAC', label: 'País de nacimiento' },
  RESIDENCIA: { code: 'RES', label: 'País de residencia' },
} as const;
export type UsoNacionalidad = CodeOf<typeof USO_NACIONALIDAD>;
export const UsoNacionalidadLabel = labelOf(USO_NACIONALIDAD);

export type NacimientoItem = {
  fecha?: Date;
  lugar?: string;
  nacionalidad?: Nacionalidad;
};
