export enum IdiomaCode {
  SPANISH = 'es',
  ENGLISH = 'en',
  PORTUGUESE = 'pt',
  FRENCH = 'fr',
  GERMAN = 'de',
  ITALIAN = 'it',
  CHINESE = 'zh',
  JAPANESE = 'ja',
  ARABIC = 'ar',
  RUSSIAN = 'ru',
  KOREAN = 'ko',
  HINDI = 'hi',
  BENGALI = 'bn',
  DUTCH = 'nl',
  SWEDISH = 'sv',
  NORWEGIAN = 'no',
  DANISH = 'da',
  FINNISH = 'fi',
  POLISH = 'pl',
  CZECH = 'cs',
  HUNGARIAN = 'hu',
  ROMANIAN = 'ro',
  BULGARIAN = 'bg',
  GREEK = 'el',
  HEBREW = 'he',
  TURKISH = 'tr',
  PERSIAN = 'fa',
  URDU = 'ur',
  THAI = 'th',
  VIETNAMESE = 'vi',
  INDONESIAN = 'id',
  MALAY = 'ms',
  TAGALOG = 'tl',
  SWAHILI = 'sw',
  CATALAN = 'ca',
  BASQUE = 'eu',
  GALICIAN = 'gl',
}

export const IdiomaCodeLabel: Record<IdiomaCode, string> = {
  [IdiomaCode.SPANISH]: 'Español',
  [IdiomaCode.ENGLISH]: 'Inglés',
  [IdiomaCode.PORTUGUESE]: 'Portugués',
  [IdiomaCode.FRENCH]: 'Francés',
  [IdiomaCode.GERMAN]: 'Alemán',
  [IdiomaCode.ITALIAN]: 'Italiano',
  [IdiomaCode.CHINESE]: 'Chino',
  [IdiomaCode.JAPANESE]: 'Japonés',
  [IdiomaCode.ARABIC]: 'Árabe',
  [IdiomaCode.RUSSIAN]: 'Ruso',
  [IdiomaCode.KOREAN]: 'Coreano',
  [IdiomaCode.HINDI]: 'Hindi',
  [IdiomaCode.BENGALI]: 'Bengalí',
  [IdiomaCode.DUTCH]: 'Neerlandés',
  [IdiomaCode.SWEDISH]: 'Sueco',
  [IdiomaCode.NORWEGIAN]: 'Noruego',
  [IdiomaCode.DANISH]: 'Danés',
  [IdiomaCode.FINNISH]: 'Finlandés',
  [IdiomaCode.POLISH]: 'Polaco',
  [IdiomaCode.CZECH]: 'Checo',
  [IdiomaCode.HUNGARIAN]: 'Húngaro',
  [IdiomaCode.ROMANIAN]: 'Rumano',
  [IdiomaCode.BULGARIAN]: 'Búlgaro',
  [IdiomaCode.GREEK]: 'Griego',
  [IdiomaCode.HEBREW]: 'Hebreo',
  [IdiomaCode.TURKISH]: 'Turco',
  [IdiomaCode.PERSIAN]: 'Persa',
  [IdiomaCode.URDU]: 'Urdu',
  [IdiomaCode.THAI]: 'Tailandés',
  [IdiomaCode.VIETNAMESE]: 'Vietnamita',
  [IdiomaCode.INDONESIAN]: 'Indonesio',
  [IdiomaCode.MALAY]: 'Malayo',
  [IdiomaCode.TAGALOG]: 'Tagalo',
  [IdiomaCode.SWAHILI]: 'Suajili',
  [IdiomaCode.CATALAN]: 'Catalán',
  [IdiomaCode.BASQUE]: 'Vasco',
  [IdiomaCode.GALICIAN]: 'Gallego',
} as const;

export enum IdiomaPreferenciaCode {
  PREFERIDO = 'PREF',
  PRIMARIO = 'PRI',
  SECUNDARIO = 'SEC',
}
export const IdiomaPreferenciaCodeLabel: Record<IdiomaPreferenciaCode, string> =
  {
    [IdiomaPreferenciaCode.PREFERIDO]: 'Preferido',
    [IdiomaPreferenciaCode.PRIMARIO]: 'Primario',
    [IdiomaPreferenciaCode.SECUNDARIO]: 'Secundario',
  } as const;

export enum IdiomaNivelCode {
  BASICO = 'BAS',
  INTERMEDIO = 'INT',
  PROFESIONAL = 'PRO',
  AVANZADO = 'AVA',
}

export const IdiomaNivelCodeLabel: Record<IdiomaNivelCode, string> = {
  [IdiomaNivelCode.BASICO]: 'Básico',
  [IdiomaNivelCode.INTERMEDIO]: 'Intermedio',
  [IdiomaNivelCode.PROFESIONAL]: 'Profesional',
  [IdiomaNivelCode.AVANZADO]: 'Avanzado',
} as const;
