import { ProvinciaCode } from "./provincia-code";

export enum CantonCode {
  LA_CONCORDIA = "08",
  LA_LIBERTAD = "02",
  QUINSALOMA = "13",
  SALINAS = "03",
  SANTA_ELENA = "01",
  SANTO_DOMINGO = "01",
  LAS_GOLONDRINAS = "01",
  MANGA_DEL_CURA = "03",
  EL_PIEDRERO = "04",
  MACHALA = "01",
  ARENILLAS = "02",
  ATAHUALPA = "03",
  BALSAS = "04",
  CHILLA = "05",
  CUENCA = "01",
  GIRON = "02",
  GUALACEO = "03",
  NABON = "04",
  PAUTE = "05",
  PUCARA = "06",
  SAN_FERNANDO = "07",
  SANTA_ISABEL = "08",
  SIGSIG = "09",
  AZOGUES = "01",
  BIBLIAN = "02",
  CANAR = "03",
  LA_TRONCAL = "04",
  MORONA = "01",
  GUALAQUIZA = "02",
  LIMON_INDANZA = "03",
  PALORA = "04",
  SANTIAGO = "05",
  SUCUA = "06",
  GUARANDA = "01",
  CHILLANES = "02",
  CHIMBO = "03",
  ECHEANDIA = "04",
  SAN_MIGUEL = "05",
  CALUMA = "06",
  LAS_NAVES = "07",
  TULCAN = "01",
  BOLIVAR = "02",
  ESPEJO = "03",
  MIRA = "04",
  MONTUFAR = "05",
  SAN_PEDRO_DE_HUACA = "06",
  LATACUNGA = "01",
  LA_MANA = "02",
  PANGUA = "03",
  PUJILI = "04",
  SALCEDO = "05",
  SAQUISILI = "06",
  SIGCHOS = "07",
  RIOBAMBA = "01",
  ALAUSI = "02",
  COLTA = "03",
  CHAMBO = "04",
  CHUNCHI = "05",
  GUAMOTE = "06",
  GUANO = "07",
  PALLATANGA = "08",
  PENIPE = "09",
  CUMANDA = "10",
  ESMERALDAS = "01",
  ELOY_ALFARO = "02",
  MUSINE = "03",
  QUININDE = "04",
  SAN_LORENZO = "05",
  ATACAMES = "06",
  GUAYAQUIL = "01",
  ALFREDO_BAQUERIZO_MORENO = "02",
  BALAO = "03",
  BALZAR = "04",
  COLIMES = "05",
  DAULE = "06",
  DURAN = "07",
  EL_EMPALME = "08",
  EL_TRIUNFO = "09",
  MILAGRO = "10",
  NARANJAL = "11",
  NARANJITO = "12",
  PALESTINA = "13",
  PEDRO_CARBO = "14",
  SALINAS_GUAYAS = "15",
  SAMBORONDON = "16",
  SANTA_ELENA_GUAYAS = "17",
  SANTA_LUCIA = "18",
  URBINA_JADO = "19",
  YAGUACHI = "20",
  PLAYAS = "21",
  SIMON_BOLIVAR = "22",
  CORONEL_MARCELINO_MARIDUENA = "23",
  LOMAS_DE_SARGENTILLO = "24",
  NOBOL = "25",
  LA_LIBERTAD_GUAYAS = "26",
  GENERAL_ANTONIO_ELIZALDE = "27",
  IBARRA = "01",
  ANTONIO_ANTE = "02",
  COTACACHI = "03",
  OTAVALO = "04"
}


export const CantonesPorProvincia: Record<ProvinciaCode, CantonCode[]> = {
  [ProvinciaCode.NACIONALIZADOS]: [],
  [ProvinciaCode.AZUAY]: [
    CantonCode.CUENCA,
    CantonCode.GIRON,
    CantonCode.GUALACEO,
    CantonCode.NABON,
    CantonCode.PAUTE,
    CantonCode.PUCARA,
    CantonCode.SAN_FERNANDO,
    CantonCode.SANTA_ISABEL,
    CantonCode.SIGSIG
  ],
  [ProvinciaCode.BOLIVAR]: [
    CantonCode.GUARANDA,
    CantonCode.CHILLANES,
    CantonCode.CHIMBO,
    CantonCode.ECHEANDIA,
    CantonCode.SAN_MIGUEL,
    CantonCode.CALUMA,
    CantonCode.LAS_NAVES
  ],
  [ProvinciaCode.CANAR]: [
    CantonCode.AZOGUES,
    CantonCode.BIBLIAN,
    CantonCode.CANAR,
    CantonCode.LA_TRONCAL
  ],
  [ProvinciaCode.CARCHI]: [
    CantonCode.TULCAN,
    CantonCode.BOLIVAR,
    CantonCode.ESPEJO,
    CantonCode.MIRA,
    CantonCode.MONTUFAR,
    CantonCode.SAN_PEDRO_DE_HUACA
  ],
  [ProvinciaCode.COTOPAXI]: [
    CantonCode.LATACUNGA,
    CantonCode.LA_MANA,
    CantonCode.PANGUA,
    CantonCode.PUJILI,
    CantonCode.SALCEDO,
    CantonCode.SAQUISILI,
    CantonCode.SIGCHOS
  ],
  [ProvinciaCode.CHIMBORAZO]: [
    CantonCode.RIOBAMBA,
    CantonCode.ALAUSI,
    CantonCode.COLTA,
    CantonCode.CHAMBO,
    CantonCode.CHUNCHI,
    CantonCode.GUAMOTE,
    CantonCode.GUANO,
    CantonCode.PALLATANGA,
    CantonCode.PENIPE,
    CantonCode.CUMANDA
  ],
  [ProvinciaCode.EL_ORO]: [
    CantonCode.MACHALA,
    CantonCode.ARENILLAS,
    CantonCode.ATAHUALPA,
    CantonCode.BALSAS,
    CantonCode.CHILLA
  ],
  [ProvinciaCode.ESMERALDAS]: [
    CantonCode.ESMERALDAS,
    CantonCode.ELOY_ALFARO,
    CantonCode.MUSINE,
    CantonCode.QUININDE,
    CantonCode.SAN_LORENZO,
    CantonCode.ATACAMES,
    CantonCode.LA_CONCORDIA
  ],
  [ProvinciaCode.GUAYAS]: [
    CantonCode.GUAYAQUIL,
    CantonCode.ALFREDO_BAQUERIZO_MORENO,
    CantonCode.BALAO,
    CantonCode.BALZAR,
    CantonCode.COLIMES,
    CantonCode.DAULE,
    CantonCode.DURAN,
    CantonCode.EL_EMPALME,
    CantonCode.EL_TRIUNFO,
    CantonCode.MILAGRO,
    CantonCode.NARANJAL,
    CantonCode.NARANJITO,
    CantonCode.PALESTINA,
    CantonCode.PEDRO_CARBO,
    CantonCode.SALINAS_GUAYAS,
    CantonCode.SAMBORONDON,
    CantonCode.SANTA_ELENA_GUAYAS,
    CantonCode.SANTA_LUCIA,
    CantonCode.URBINA_JADO,
    CantonCode.YAGUACHI,
    CantonCode.PLAYAS,
    CantonCode.SIMON_BOLIVAR,
    CantonCode.CORONEL_MARCELINO_MARIDUENA,
    CantonCode.LOMAS_DE_SARGENTILLO,
    CantonCode.NOBOL,
    CantonCode.LA_LIBERTAD_GUAYAS,
    CantonCode.GENERAL_ANTONIO_ELIZALDE
  ],
  [ProvinciaCode.IMBABURA]: [
    CantonCode.IBARRA,
    CantonCode.ANTONIO_ANTE,
    CantonCode.COTACACHI,
    CantonCode.OTAVALO
  ],
  [ProvinciaCode.LOJA]: [],
  [ProvinciaCode.LOS_RIOS]: [
    CantonCode.QUINSALOMA
  ],
  [ProvinciaCode.MANABI]: [],
  [ProvinciaCode.MORONA_SANTIAGO]: [
    CantonCode.MORONA,
    CantonCode.GUALAQUIZA,
    CantonCode.LIMON_INDANZA,
    CantonCode.PALORA,
    CantonCode.SANTIAGO,
    CantonCode.SUCUA
  ],
  [ProvinciaCode.NAPO]: [],
  [ProvinciaCode.PASTAZA]: [],
  [ProvinciaCode.PICHINCHA]: [],
  [ProvinciaCode.TUNGURAHUA]: [],
  [ProvinciaCode.ZAMORA_CHINCHIPE]: [],
  [ProvinciaCode.GALAPAGOS]: [],
  [ProvinciaCode.SUCUMBIOS]: [],
  [ProvinciaCode.ORELLANA]: [],
  [ProvinciaCode.SANTO_DOMINGO_DE_LOS_TSACHILAS]: [
    CantonCode.SANTO_DOMINGO
  ],
  [ProvinciaCode.SANTA_ELENA]: [
    CantonCode.LA_LIBERTAD,
    CantonCode.SALINAS,
    CantonCode.SANTA_ELENA
  ],
  [ProvinciaCode.ZONAS_NO_DELIMITADAS]: [
    CantonCode.LAS_GOLONDRINAS,
    CantonCode.MANGA_DEL_CURA,
    CantonCode.EL_PIEDRERO
  ]
};