import { ProvinciaCode } from "./provincia-code";

export const ProvinciaCodeLabels: Record<ProvinciaCode, string> = {
  [ProvinciaCode.NACIONALIZADOS]: "Nacionalizados",
  [ProvinciaCode.AZUAY]: "Azuay",
  [ProvinciaCode.BOLIVAR]: "Bolívar",
  [ProvinciaCode.CANAR]: "Cañar",
  [ProvinciaCode.CARCHI]: "Carchi",
  [ProvinciaCode.COTOPAXI]: "Cotopaxi",
  [ProvinciaCode.CHIMBORAZO]: "Chimborazo",
  [ProvinciaCode.EL_ORO]: "El Oro",
  [ProvinciaCode.ESMERALDAS]: "Esmeraldas",
  [ProvinciaCode.GUAYAS]: "Guayas",
  [ProvinciaCode.IMBABURA]: "Imbabura",
  [ProvinciaCode.LOJA]: "Loja",
  [ProvinciaCode.LOS_RIOS]: "Los Ríos",
  [ProvinciaCode.MANABI]: "Manabí",
  [ProvinciaCode.MORONA_SANTIAGO]: "Morona Santiago",
  [ProvinciaCode.NAPO]: "Napo",
  [ProvinciaCode.PASTAZA]: "Pastaza",
  [ProvinciaCode.PICHINCHA]: "Pichincha",
  [ProvinciaCode.TUNGURAHUA]: "Tungurahua",
  [ProvinciaCode.ZAMORA_CHINCHIPE]: "Zamora-Chinchipe",
  [ProvinciaCode.GALAPAGOS]: "Galápagos",
  [ProvinciaCode.SUCUMBIOS]: "Sucumbíos",
  [ProvinciaCode.ORELLANA]: "Orellana",
  [ProvinciaCode.SANTO_DOMINGO_DE_LOS_TSACHILAS]: "Santo Domingo de los Tsáchilas",
  [ProvinciaCode.SANTA_ELENA]: "Santa Elena",
  [ProvinciaCode.ZONAS_NO_DELIMITADAS]: "Zonas no delimitadas"
};
